FORBIDDEN_TERMS = [
    "as we continue to push...",
    "it's crucial to...",
    "delve",
    "Tapestry",
    "Vibrant",
    "Landscape",
    "Realm",
    "Embark",
    "Vital",
    "Moreover",
    "Arguably",
    "Dive into...",
    "It’s important to note...",
    "Important to consider...",
    "Based on the information provided...",
    "Remember that...",
    "Navigating the [landscape]/[complexities of]...",
    "A testament to...",
    "Elevate",
    "Explore",
    "Discover",
    "Unleash",
    "Unveiled",
    "Picture this...",
    "Plethora",
    "Top-notch",
    "Treasure trove",
    "In today’s digital era...",
    "Revolutionize",
    "Game changer",
    "Cutting-edge",
    "forefront",
    "resonate",
    "Captivate",
    "It’s important to note",
    "Master the art of",
    "In the dynamic world of",
    "A treasure trove of",
    "As we venture",
]
